# Generated by Django 3.1.7 on 2021-03-31 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('review', models.CharField(choices=[('P', 'Poor'), ('O', 'Okay'), ('G', 'Good'), ('F', 'Fantastic')], default='G', max_length=1)),
                ('chip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.chip')),
            ],
        ),
    ]
