# Generated by Django 3.1.7 on 2021-04-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateField(verbose_name='review date'),
        ),
    ]
