# Generated by Django 3.1.7 on 2021-04-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210401_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='chip',
            name='stores',
            field=models.ManyToManyField(to='main_app.Store'),
        ),
    ]
